language: node_js

node_js:
  - "10"
  - "12"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g yarn@latest

install:
  - yarn

script:
  - yarn build:ci

git:
  depth: 1
